src/adapters/lambda-invocation.js, src/adapters/response-retry.js, test/lambda-invoke-retry.test.js
This adds a test and fixes the behavior for invocations that combine both timeout and retry options. The client should retry timed out lambda invocations without a custom retryCondition parameter.
=> Retry Lambda function invocations that time out

src/adapters/lambda-invocation.js, test/lambda-invocation.test.js
This change was motivated to avoid the situation shown in the screenshot: 
In that case, a short timeout was handled at ~900 ms, but the Lambda invoke continued to execute. This new code to set the HTTP level timeouts is here to help the low level systems quickly clean themselves up.
=> Set HTTP client timeout options for Lambda invoke calls

package.json, src/adapters/lambda-invocation.js, test/lambda-invocation.test.js
Be a good citizen to cleanup timers as soon as they are no longer used. Without this change, a process that is 'done' could stay executing until the timeout happens just to wait for the timer to complete and do nothing.
=> Cleanup timers when Lambda invoke completes

.gitignore, package.json, src/adapters/helpers/lambdaURL.ne, src/adapters/helpers/parseLambdaUrl.js, test/parseLambdaUrl.test.js, yarn.lock
This will allow for URLs like:
`lambda://<accountId>:function:<functionName>/`
`lambda://arn:aws:lambda:<region>:<accountId>:function:<functionName>/`
=> Allow partial and full function ARNs in the lambda URL scheme

package.json, src/Alpha.js, src/adapters/alpha-config.js, src/adapters/helpers/chainAdapters.js, src/adapters/index.js, yarn.lock
Axios has begun stripping unknown configuration options off of the
config object. Alpha depends on some custom configuration options.
This change introduces an adapter that packs Alpha config into
the adapter attribute.
=> Upgrade to latest Axios

package.json, src/Alpha.js, src/adapters/helpers/lambdaEvent.js, test/lambda-invocation.test.js, test/parseLambdaUrl.test.js, test/resolve.test.js, yarn.lock
Node 11 deprecated url.parse() and url.resolve(). They expect the WHATWG-compatible URL module to be the replacement, but it throws errors when provided with basic paths. To solve that, I've added two new dependencies that mimic the behavior of url.parse() and url.resolve().
Please review the change to Alpha.js and confirm if I've covered the cases where we'll want to use the path resolution behavior. I'm not sure if it's more correct to do it this way, or detecting the absence of the 'http' prefix in the string.
I also removed the dependency on `whatwg-url` since Node now provides its own module that does the same thing.
Fixes #30  
Fixes #27
=> Bump ESLint, fix deprecation warnings for url.parse() and url.resolve(), remove whatwg-url

package.json
This is the greenkeeper suggestion for triage, which seems like a great idea while we track down how to play nicely with axios 0.19.1.
=> chore: pin axios to 0.19.0

package.json, src/adapters/lambda-invocation.js, yarn.lock
Axios adjusted how it handled `url` and `baseURL` in the patch update from 0.19.0 to 0.19.1.  This prevented the `lambda-invocation` adapter from being invoked for certain Alpha configurations.
See [this test](https://github.com/axios/axios/blob/351cf290f0478d6e47e74c6da2f3ad8fe8f29887/test/unit/adapters/http.js#L650) as a reference to what was introduced in the patch.
=> Adds support for axios 0.19.1

.travis.yml
See the error: https://travis-ci.org/lifeomic/alpha/jobs/649510935#L386
Deployment V2 docs: https://docs.travis-ci.com/user/deployment-v2
@aiwilliams figured out this fix on an open source JupiterOne integration so supersized McThankies go to him. Also note, this will require me to cut another patch version so that Travis deploys the changes in the previous PR.
=> Enable Travis deployment v2 to fix api_key error

src/adapters/helpers/promisify.js, test/lambda-handler.test.js
This is to make testing easier for consuming projects. Our internal shared serverless-http based Koa app only exports a promise-style handler function now. Previously, Alpha only supported callback style because the injected callback below would never get called for a promise style handler. The new way will allow for either.
=> support both callback and promise style local test handler

CHANGELOG.md, package.json, src/Alpha.d.ts
It's common for consumers to import `AxiosInstance` from `axios` to properly type instances of `Alpha`. By not exporting from `@lifeomic/alpha` directly, it's very easy to have a mismatch between alpha's version of axios types and the consuming project's root level version of axios types. Using the exposed type should help avoid a lot of mismatches.
=> Export more types to avoid mismatch with axios version juggling

CHANGELOG.md, package.json, src/Alpha.d.ts
This is a follow-up to https://github.com/lifeomic/alpha/pull/69
I thought I linked/tested the previous change and it worked. I think I forgot to run `yarn prepare` when linking in the consuming project. I verified three times, this time :)
Module declarations don't support a default export in addition to named exports: `An export assignment cannot be used in a module with other exported elements.`
I can't think of a good reason to use the `declare module` syntax here (I generally avoid this pattern elsewhere), but I'm also not a TS expert. I'd love to get feedback from at least a couple of people in case I'm missing something obvious here.
=> Fix types - move away from module declarations

.github/workflows/release.yaml
Previous publish behavior did not go as planned: https://github.com/lifeomic/alpha/pull/79/checks
CC @anthonyroach I think the config in @lifeomic/abac may cause some unintended side effects without the master filter (in my case, pushing the tag on a non-master branch published it directly). Also, the custom scripts that exit with status=0 don't actually do anything. Subsequent steps continued executing - see above PR logs for example (it tried to publish 3 times)
=> Only publish on master branch

CHANGELOG.md, package.json, src/adapters/helpers/lambdaEvent.js, yarn.lock
Fixed a url parsing bug  exposed by the newest url-parse module which
caused the URL passed to the lambda to be missing a leading forward
slash.
=> Fixed a url parsing bug

src/adapters/helpers/parseLambdaUrl.js, test/parseLambdaUrl.test.js
Background:
`cohorts-service` is doing validation that all patients in a cohort belong to the same project as the cohort. For sufficiently large cohorts with thousands of patients this can take several seconds to perform the validation because of a delay in retrieving the patients from `patient-service`.
However, using Axios to request the patients from `patient-service` instead of Alpha can reduce that time to a second.
I ran some benchmarks in Alpha and found that the Nearley parser is the bottleneck. By removing the query string from the url before parsing it and then appending it to the end of the path part afterward reduces the time back down to a second. Admittedly, I'm not the biggest fan of this solution. 
Other options; 
* Use Axios instead of Alpha to do the validation in …
=> LO-1156 - Reduce risk of performance degradation on urls with large query string params

package.json, src/adapters/helpers/lambdaEvent.js, test/lambda-event.test.js, test/lambda-handler.test.js
This is an attempt to fix a bug when invoking a handler created with `apollo-server-lambda` v3. 
`apollo-server-lambda` v3 uses `@vendia/serverless-express` under the hood which expects a requestContext field on the lambda event or else it fails to determine the event source.
https://github.com/vendia/serverless-express/issues/416
=> Add requestContext to lambda event to support apollo-server-lambda

package.json, src/adapters/helpers/lambdaEvent.js, test/lambda-event.test.js, test/lambda-handler.test.js, yarn.lock
The LifeOmic request processing uses the request ID attribute from
the APIG event payload as the default value for correlation IDs.
When an Alpha request is the root event in a tree of requests this
means that there is no correlation ID generated for the entire
tree.
Generating a request ID on Alpha requests will allow the LO
machinery to infer and propagate an correlation ID when Alpha is
the originator of the request.
=> Generate a random request ID

.github/workflows/pr-branch-build.yaml, README.md, package.json, src/adapters/helpers/lambdaEvent.js, test/lambda-event.test.js, test/lambda-handler.test.js
This adds one more thing to make `alpha.post(handler)` requests work with `apollo-server-lambda` v3 handlers.
=> Add multiValueHeaders field to API Gateway event.

README.md, package.json, src/Alpha.d.ts, src/adapters/lambda-invocation.js, test/lambda-invocation.test.js
Currently the only way to choose the lambda endpoint is with the `LAMBDA_ENDPOINT` env var. This works fine when you only have a single endpoint, but fails when you have multiple endpoints. With this change you can invoke multiple dockerized lambdas hosted at different endpoints using the `lambdaEndpoint` config option.
=> Add config option for the aws lambda endpoint.

src/index.ts
In particular, `AlphaOptions` was lost in the v4 TypeScript re-write. Just re-adding some root-level exports here.
=> feat: expose types

.github/workflows/pr-branch-build.yaml, jest.config.ts, package.json, src/adapters/helpers/lambdaResponse.ts, src/adapters/helpers/requestError.ts, src/adapters/lambda-invocation.ts, src/alpha.ts, src/types.ts, test/lambda-invocation.test.ts, test/lambda-invoke-retry.test.ts, test/redirects.test.ts, test/setup.ts, test/utils.ts, tsconfig.json, yarn.lock
The aws-sdk adds almost 16MB.
Also drop support for node 12.
=> Drop aws-sdk and use @aws-sdk/client-lambda

package.json, yarn.lock
I'm not sure why `docker-lambda` was still present.  This also closes #138, which is failing.
=> Clean up dependencies.  Some are not being used

src/adapters/lambda-handler.ts, test/lambda-handler.test.ts
- Added error response when throwing request error
- Added unit test
I noticed when updating lambda-tools along with alpha for integration tests within content service that some of our integration tests failed because response was undefined. I did some digging and that led me here.
=> fix: Adding response to request error

src/adapters/lambda-invocation.ts
Running without the destroy leaves open sockets between invocations.  The notes advise to call destroy to avoid long running sockets.  Through my testing just calling ListFunctions we end up with 2 open sockets up to 100, then an additional socket with every invocation.  Not sure how long the sockets are left open.
=> fix: Need to call destroy to cleanup after creation

package.json, yarn.lock
A duplicate of #155, but with a signed commit.
=> fix: add @aws-sdk/url-parser as explicit dependency

.github/workflows/pr-branch-build.yaml, package.json
This declares `axios` as a production dependency, rather than a `peerDependency`.
This PR aims to address a few consistent pain points I've experienced as a result of using `axios` as a peer dependency here.
**Current Problems**
- It is painful to need to maintain `alpha` typedefs that are compatible with _multiple_ versions of `axios`.
- Currently, any developer who wants to make us of both `alpha` _and_ `axios` directly within a single project _must_ only use a version of `axios` that `alpha` supports.
- Currently, the versions of `axios` that `alpha` supports are a long way behind the latest `axios` versions. And, the latest versions of `axios` are _incompatible_ with the current version of `alpha` -- so it is not as simple as e.g. `yarn add axios @lifeomic/alpha`. Rather, as a …
=> feat: declare axios as a production dependency

release.config.js
Adding support for publishing alpha pre-releases. I plan to add one with axios set to 0.28 so upstream consumers can safely resolve security updates.
=> chore: support alpha releases

.github/workflows/release.yaml
Missed this to make alpha releases actually run.
=> chore: [pt. 2] support alpha release

src/interceptors/aws-v4-signature.ts
Alpha does not work well in a non-ESM because Axios, upstream, adopted ESM in their "unsafe" published source files. This sort of failure is common when adopting the latest Alpha version:
```
/Users/mattlavin/Projects/graphql-tools-cli/node_modules/@lifeomic/alpha/src/interceptors/aws-v4-signature.js:11
const buildURL_js_1 = __importDefault(require("axios/unsafe/helpers/buildURL.js"));
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mattlavin/Projects/graphql-tools-cli/node_modules/axios/lib/helpers/buildURL.js from /Users/mattlavin/Projects/graphql-tools-cli/node_modules/@lifeomic/alpha/src/interceptors/aws-v4-signature.js not supported.
```
Luckily, the only place that "unsafe" (aka ESM) modules are imported is in the AWS V4 signing support and that is very infrequently used. …
=> Avoid ESM failures when AWS V4 signing is unused

.prettierrc, src/adapters/helpers/lambdaResponse.ts, test/lambda-invocation.test.ts
Sometimes I see errors like this in logs:
```
"Error: Request failed with status code 404
at lambdaResponse (/node_modules/@lifeomic/alpha/lib/adapters/helpers/lambdaResponse.js:17:11)
at <anonymous> (/node_modules/@lifeomic/alpha/lib/adapters/lambda-invocation.js:87:12)
```
These^ error messages don't give any info about which line threw the error, or what Lambda URL was being called. This change will make that error message look like `Error: Request GET lambda://test-function/some/path failed with status code 400`, which provides more helpful debug information.
=> fix: include method and url in request error message

src/adapters/helpers/lambdaEvent.ts, test/lambda-event.test.ts
According to the [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format) a multi-value param should be separated by commas for the `queryStringParameters` field and all fields should be formatted as an array for `multiValueQueryStringParameters`. In my testing it seems that our lambdas take one or the other so all values should exist in both. 
I set the `multiValueQueryStringParameters` to null when there are no multi fields.
=> fix: multiValueQueryStringParameters should be null if empty

src/adapters/helpers/lambdaEvent.ts, test/lambda-event.test.ts
With version 7.0.1 a query string like `?a=1&a=2&b=3` would produce params like
```javascript
{
queryStringParameters: { a: '1,2', b: '3' },
multiValueQueryStringParameters: { a: ['1', '2'], b: ['3'] },
}
```
This change causes it to produce params like 
```javascript
{
queryStringParameters: { b: '3' },
multiValueQueryStringParameters: { a: ['1', '2'] },
}
```
The [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html) on the API Gateway Event does not provide details on what the expected function of each of these is so I am looking for input as well as proposing one potential solution (this PR). Here are the options as I see it.
1. Have alpha create events where array values are exclusively in `multiValueQueryStringParameters` …
=> Don't duplicate Lambda Event Params

src/adapters/helpers/lambdaEvent.ts, test/lambda-event.test.ts
This reverts the logic to split query params into separate variables because it is not backwards compatible with older services.
Koa has been [updated](https://github.com/lifeomic/koa/pull/161) to continue to support array values in `queryStringParameters` so these changes are no longer needed.
=> fix: Remove multiValueQueryStringParameters Logic

src/alpha.ts, test/redirects.test.ts
`graphql-proxy-service` will sometimes error with a `RangeError: Maximum call stack size exceeded`. The log's call stack points to an infinite recursive loop within the @lifeomic/alpha client's request method. 
The errors occur in the chat agent callstack from various user-agents but its very difficult to tell why. ([logs](https://service.us2.sumologic.com/log-search/create?id=T3LyoJ0MRMV32FtSts9orO3Rvz0TQlBMgOn6PPQD)). Bugsnag is reporting these as 502's from flma, but from the logs we can see its not limited to the member app.
Looking back in the logs and matching up dates with changes, it also may have started after introducing [thinking mode](https://github.com/lifeomic/agents/pull/1034). 
Reviewing the code, the conclusion is that the client is receiving a 301 or 302 response, …
=> [EOCI-745] prevent recursive range error on redirects
